rel:
	@cd venc;   make
	@cd audio;  make
	@cd region;  make

clean:
	@cd venc;   make clean
	@cd audio;  make clean
	@cd region;  make clean

cleanall:
	@cd venc;   make clean;   make cleanstream
	@cd audio;  make clean;   make cleanstream
	@cd region;  make clean;   make cleanstream

