#ifndef COMMAND_DEFINE_H
#define COMMAND_DEFINE_H

typedef enum 
{
	IOTYPE_USER_IPCAM_VIDEOSTART 				= 0x01FF,	//开启流
	IOTYPE_USER_IPCAM_VIDEOSTART_RESP 			= 0x0200,	//开启流应答
	IOTYPE_USER_IPCAM_VIDEOSTOP	 				= 0x0201,	//关闭流
	IOTYPE_USER_IPCAM_VIDEOSTOP_RESP	 		= 0x0202,	//关闭流
	IOTYPE_USER_IPCAM_AUDIOSTART 				= 0x0203,	//开启音频	
	IOTYPE_USER_IPCAM_AUDIOSTART_RESP 			= 0x0204,	//开启音频	
	IOTYPE_USER_IPCAM_AUDIOSTOP 				= 0x0205,	//关闭音频
	IOTYPE_USER_IPCAM_AUDIOSTOP_RESP 			= 0x0206,	//关闭音频
	IOTYPE_USER_IPCAM_SPEAKERSTART 				= 0x0207,	//开启对讲
	IOTYPE_USER_IPCAM_SPEAKERSTART_RESP			= 0x0208,	//开启对讲
	IOTYPE_USER_IPCAM_SPEAKERSTOP 				= 0x0209,	//关闭对讲
	IOTYPE_USER_IPCAM_SPEAKERSTOP_RESP 			= 0x0210,	//关闭对讲


	TMP_IOTYPE_USER_IPCAM_STOP	 					= 0x02FF,	//关闭流
	TMP_IOTYPE_USER_IPCAM_AUDIOSTART 				= 0x0300,	//开启音频	
	TMP_IOTYPE_USER_IPCAM_AUDIOSTOP 				= 0x0301,	//关闭音频
}ENUM_COMMAND_DEFINE; //APP don't use it now

#endif
